{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "config-reporter.name" . }}-binding
  labels:
    {{- include "config-reporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "config-reporter.name" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "config-reporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}