{{- if .Values.serviceMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "config-reporter.name" . }}-monitor
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  labels:
    {{- include "config-reporter.labels" . | nindent 4 }}
    release: prometheus
    app: {{ include "config-reporter.name" . }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "config-reporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: "metrics"
    path: "/metrics"
{{- end -}}
