---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-viewer
  namespace: resource-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: resource-tools
  name: config-viewer-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: config-viewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: config-viewer-role
subjects:
- kind: ServiceAccount
  name: config-viewer
  namespace: resource-tools
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: k8s-config-test
  name: k8s-config-test
  namespace: resource-tools
spec:
  serviceAccountName: config-viewer
  containers:
  - image: garnaalkroket/k8s-config-reporter:0.1.0
    name: k8s-config-test
    env:
    - name: "AUTH_METHOD"
      value: "cluster"
    - name: "CONFIGMAP_NAME"
      value: "environment"
    - name: "CONFIGMAP_KEYS"
      value: "profile.resources,profile.azure"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
